// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufksfnzzgjqpsabmrkre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVma3Nmbnp6Z2pxcHNhYm1ya3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDY3MDEsImV4cCI6MjA2NzE4MjcwMX0.cM17H3Em8DRkHqBXRfgCYOvkoO_gvmVm9Q9nyrfN8q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});